### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by THE-ASHUTOSH** [ats633/serial-killer-stats#3]
I can contribute to make the UI more attractive.
Please assign me this so that I can start working on this.
Thank You

**Comment by ats633** [comment]
> I can contribute to make the UI more attractive. Please assign me this so that I can start working on this. Thank You

Here ya go bortweewee

**Comment by THE-ASHUTOSH** [comment]
Your file names are very miss matched. I have to edit each and everything from the scratch. It also has many errors in it.
If you allow to make changes in all the file than I would like to continue with the project.

**Comment by ats633** [comment]
> Your file names are very miss matched. I have to edit each and everything from the scratch. It also has many errors in it. If you allow to make changes in all the file than I would like to continue with the project.

Yeah do what you need to do, do I need to give you permissions for the main files or anything? I've only been on Github for like 2 days bro

**Comment by THE-ASHUTOSH** [comment]
No problem, I will figure it out by tomorrow and let you know.

**Comment by THE-ASHUTOSH** [comment]
Just accept the pull request

**Comment by THE-ASHUTOSH** [comment]
What will you rate me for my work
